// Card -> full-stack reward, for cards whose reward is a plain, individually
// priceable item. Sourced from poedb.tw/us/Divination_Cards - poe.ninja has
// no API for this mapping (its exchange "details" endpoint only returns
// bulk-exchange trading rates for the card itself, not what it converts into).
//
// This is static game data (reward + stack size don't change with league), so
// it's safe to hardcode - only the live price of the reward item is fetched.
// Cards that give a random/non-specific reward (e.g. "Currency", "Essence",
// "Oil" without a tier) are intentionally omitted since there's no single item
// to price. GGG occasionally rebalances card rewards between leagues - verify
// here if a row looks off, and update as needed.
//
// `category` is the poe.ninja economy category the reward item itself lives
// in - most currency rewards are plain "Currency", but several league-
// mechanic items (fragments, essences, fossils, delirium orbs, vials,
// tattoos) are their own category and 404 if queried as Currency. Unique-item
// rewards use "UniqueWeapon" / "UniqueArmour" / "UniqueAccessory" /
// "UniqueJewel" / "UniqueFlask" depending on equip slot - these five plus the
// per-item slot assignment below are unverified against the live API (not
// reachable from the environment that generated this file) and sourced from
// general game knowledge instead of a scrape, so treat them as a best effort.
// A wrong/uncertain guess anywhere here is safe: it just shows as "price
// unavailable" rather than a wrong number (OpportunityTable never falls back
// to a made-up price) - if a whole category (e.g. every UniqueWeapon row)
// comes back unpriced, that category string is probably wrong and worth
// fixing; if it's an isolated item, the slot guess for that one is probably
// wrong.
export interface DivinationCardReward {
  stackSize: number;
  rewardQuantity: number;
  rewardName: string;
  category: string;
}

export const DIVINATION_CARD_REWARDS: Record<string, DivinationCardReward> = {
  "A Dab of Ink": { stackSize: 9, rewardQuantity: 1, rewardName: "The Poet's Pen", category: "UniqueWeapon" },
  "A Modest Request": { stackSize: 3, rewardQuantity: 1, rewardName: "Megalomaniac", category: "UniqueJewel" },
  "A Mother's Parting Gift": { stackSize: 6, rewardQuantity: 1, rewardName: "Fertile Mind", category: "UniqueJewel" },
  "A Note in the Wind": { stackSize: 4, rewardQuantity: 1, rewardName: "Asenath's Mark", category: "UniqueAccessory" },
  "A Sea of Blue": { stackSize: 3, rewardQuantity: 13, rewardName: "Orb of Alteration", category: "Currency" },
  "Abandoned Wealth": { stackSize: 5, rewardQuantity: 3, rewardName: "Exalted Orb", category: "Currency" },
  "Acclimatisation": { stackSize: 2, rewardQuantity: 20, rewardName: "Orb of Alteration", category: "Currency" },
  "Alivia's Grace": { stackSize: 6, rewardQuantity: 1, rewardName: "Queen of the Forest", category: "UniqueArmour" },
  "Alluring Bounty": { stackSize: 7, rewardQuantity: 10, rewardName: "Exalted Orb", category: "Currency" },
  "Altered Perception": { stackSize: 3, rewardQuantity: 1, rewardName: "Simulacrum", category: "Fragment" },
  "Ambitious Obsession": { stackSize: 4, rewardQuantity: 1, rewardName: "Skittering Delirium Orb", category: "DeliriumOrb" },
  "Anarchy's Price": { stackSize: 13, rewardQuantity: 1, rewardName: "Voltaxic Rift", category: "UniqueWeapon" },
  "Apocalypse": { stackSize: 2, rewardQuantity: 1, rewardName: "Eyes of the Greatwolf", category: "UniqueArmour" },
  "Assassin's Gift": { stackSize: 9, rewardQuantity: 1, rewardName: "Divinarius", category: "UniqueWeapon" },
  "Audacity": { stackSize: 5, rewardQuantity: 1, rewardName: "Doryani's Fist", category: "UniqueArmour" },
  "Avian Pursuit": { stackSize: 3, rewardQuantity: 1500, rewardName: "Vivid Crystallised Lifeforce", category: "Currency" },
  "Broken Truce": { stackSize: 5, rewardQuantity: 1, rewardName: "Cold Iron Point", category: "UniqueWeapon" },
  "Brother's Gift": { stackSize: 1, rewardQuantity: 5, rewardName: "Divine Orb", category: "Currency" },
  "Brother's Stash": { stackSize: 1, rewardQuantity: 5, rewardName: "Exalted Orb", category: "Currency" },
  "Brotherhood in Exile": { stackSize: 5, rewardQuantity: 1, rewardName: "One With Nothing", category: "UniqueArmour" },
  "Burning Blood": { stackSize: 6, rewardQuantity: 1, rewardName: "Xoph's Blood", category: "UniqueAccessory" },
  "Chaotic Disposition": { stackSize: 1, rewardQuantity: 5, rewardName: "Chaos Orb", category: "Currency" },
  "Checkmate": { stackSize: 8, rewardQuantity: 76, rewardName: "Simulacrum Splinter", category: "Fragment" },
  "Choking Guilt": { stackSize: 6, rewardQuantity: 1, rewardName: "Stranglegasp", category: "UniqueAccessory" },
  "Coveted Possession": { stackSize: 9, rewardQuantity: 5, rewardName: "Regal Orb", category: "Currency" },
  "Cursed Words": { stackSize: 13, rewardQuantity: 1, rewardName: "Maw of Mischief", category: "UniqueArmour" },
  "Damnation": { stackSize: 16, rewardQuantity: 1, rewardName: "The Original Scripture", category: "UniqueWeapon" },
  "Dark Temptation": { stackSize: 5, rewardQuantity: 1, rewardName: "Obliteration", category: "UniqueWeapon" },
  "Darker Half": { stackSize: 3, rewardQuantity: 5, rewardName: "Eldritch Chaos Orb", category: "Currency" },
  "Deadly Joy": { stackSize: 6, rewardQuantity: 1, rewardName: "Torrent's Reclamation", category: "UniqueArmour" },
  "Death": { stackSize: 4, rewardQuantity: 1, rewardName: "Mon'tregul's Grasp", category: "UniqueArmour" },
  "Dementophobia": { stackSize: 11, rewardQuantity: 10, rewardName: "Delirium Orb", category: "DeliriumOrb" },
  "Demigod's Wager": { stackSize: 7, rewardQuantity: 1, rewardName: "Orb of Annulment", category: "Currency" },
  "Desperate Crusade": { stackSize: 3, rewardQuantity: 1, rewardName: "Prism Guardian", category: "UniqueArmour" },
  "Disdain": { stackSize: 5, rewardQuantity: 1, rewardName: "Delirium Orb", category: "DeliriumOrb" },
  "Divine Beauty": { stackSize: 12, rewardQuantity: 7, rewardName: "Divine Orb", category: "Currency" },
  "Divine Justice": { stackSize: 1, rewardQuantity: 1, rewardName: "Grand Spectrum", category: "UniqueJewel" },
  "Divine Shard": { stackSize: 3, rewardQuantity: 1, rewardName: "Divine Vessel", category: "Fragment" },
  "Echoes of Love": { stackSize: 3, rewardQuantity: 1, rewardName: "Fidelitas' Spike", category: "UniqueWeapon" },
  "Emperor's Luck": { stackSize: 5, rewardQuantity: 5, rewardName: "Currency", category: "Currency" },
  "Endless Night": { stackSize: 7, rewardQuantity: 1, rewardName: "Maloney's Mechanism", category: "UniqueAccessory" },
  "Energy Sword": { stackSize: 3, rewardQuantity: 1, rewardName: "Ephemeral Edge", category: "UniqueWeapon" },
  "Etched in Blood": { stackSize: 9, rewardQuantity: 1, rewardName: "Rigwald's Quills", category: "UniqueWeapon" },
  "Eternal Bonds": { stackSize: 4, rewardQuantity: 1, rewardName: "Replica Cortex", category: "UniqueAccessory" },
  "Ever-Changing": { stackSize: 3, rewardQuantity: 10, rewardName: "Orb of Unmaking", category: "Currency" },
  "Father's Love": { stackSize: 2, rewardQuantity: 1, rewardName: "Sublime Vision", category: "UniqueArmour" },
  "Fire Of Unknown Origin": { stackSize: 7, rewardQuantity: 1, rewardName: "Nimis", category: "UniqueAccessory" },
  "Forbidden Power": { stackSize: 4, rewardQuantity: 1, rewardName: "Balefire", category: "UniqueWeapon" },
  "Friendship": { stackSize: 3, rewardQuantity: 1, rewardName: "Aul's Uprising", category: "UniqueAccessory" },
  "From Bone to Ashes": { stackSize: 8, rewardQuantity: 1, rewardName: "Ngamahu's Flame", category: "UniqueWeapon" },
  "Gift of Asenath": { stackSize: 5, rewardQuantity: 1, rewardName: "Asenath's Gentle Touch", category: "UniqueArmour" },
  "Harmony of Souls": { stackSize: 9, rewardQuantity: 9, rewardName: "Shrieking Essence", category: "Essence" },
  "History": { stackSize: 5, rewardQuantity: 2, rewardName: "Hinekora's Lock", category: "Currency" },
  "House of Mirrors": { stackSize: 9, rewardQuantity: 1, rewardName: "Mirror of Kalandra", category: "Currency" },
  "Humility": { stackSize: 9, rewardQuantity: 1, rewardName: "Tabula Rasa", category: "UniqueArmour" },
  "Hunter's Reward": { stackSize: 3, rewardQuantity: 1, rewardName: "The Taming", category: "UniqueAccessory" },
  "I See Brothers": { stackSize: 2, rewardQuantity: 2, rewardName: "Fracturing Orb", category: "Currency" },
  "Imperfect Memories": { stackSize: 5, rewardQuantity: 1, rewardName: "Astrolabe", category: "Currency" },
  "Judging Voices": { stackSize: 9, rewardQuantity: 1, rewardName: "Forbidden Shako", category: "UniqueArmour" },
  "Last Stand": { stackSize: 3, rewardQuantity: 1, rewardName: "The Surrender", category: "UniqueArmour" },
  "Lethean Temptation": { stackSize: 6, rewardQuantity: 1, rewardName: "Nebulis", category: "UniqueAccessory" },
  "Lonely Warrior": { stackSize: 10, rewardQuantity: 1, rewardName: "Defiance of Destiny", category: "UniqueArmour" },
  "Love Through Ice": { stackSize: 4, rewardQuantity: 1, rewardName: "Unnatural Instinct", category: "UniqueJewel" },
  "Loyalty": { stackSize: 5, rewardQuantity: 3, rewardName: "Orb of Fusing", category: "Currency" },
  "Lucky Bastion": { stackSize: 6, rewardQuantity: 1, rewardName: "Svalinn", category: "UniqueArmour" },
  "Lucky Connections": { stackSize: 7, rewardQuantity: 20, rewardName: "Orb of Fusing", category: "Currency" },
  "Lucky Deck": { stackSize: 9, rewardQuantity: 10, rewardName: "Stacked Deck", category: "Currency" },
  "Luminous Trove": { stackSize: 7, rewardQuantity: 1, rewardName: "Voices", category: "UniqueJewel" },
  "Mawr Blaidd": { stackSize: 16, rewardQuantity: 1, rewardName: "Eyes of the Greatwolf", category: "UniqueArmour" },
  "Might is Right": { stackSize: 9, rewardQuantity: 1, rewardName: "Trypanon", category: "UniqueWeapon" },
  "Misery in Darkness": { stackSize: 6, rewardQuantity: 1, rewardName: "Shroud of the Lightless", category: "UniqueArmour" },
  "Monochrome": { stackSize: 3, rewardQuantity: 1, rewardName: "Valdo's Puzzle Box", category: "Currency" },
  "No Traces": { stackSize: 9, rewardQuantity: 30, rewardName: "Orb of Scouring", category: "Currency" },
  "Outfoxed": { stackSize: 2, rewardQuantity: 1, rewardName: "Veiled Exalted Orb", category: "Currency" },
  "Pearls Before Swine": { stackSize: 3, rewardQuantity: 1, rewardName: "Progenesis", category: "UniqueFlask" },
  "Poisoned Faith": { stackSize: 8, rewardQuantity: 1, rewardName: "Arakaali's Fang", category: "UniqueWeapon" },
  "Pride Before the Fall": { stackSize: 8, rewardQuantity: 1, rewardName: "Kaom's Heart", category: "UniqueArmour" },
  "Pride of the First Ones": { stackSize: 7, rewardQuantity: 1, rewardName: "Farrul's Fur", category: "UniqueArmour" },
  "Rain of Chaos": { stackSize: 8, rewardQuantity: 1, rewardName: "Chaos Orb", category: "Currency" },
  "Rats": { stackSize: 8, rewardQuantity: 1, rewardName: "Rat's Nest", category: "UniqueArmour" },
  "Rebirth": { stackSize: 27, rewardQuantity: 1, rewardName: "Charan's Sword", category: "UniqueWeapon" },
  "Reckless Ambition": { stackSize: 6, rewardQuantity: 1, rewardName: "Omeyocan", category: "UniqueArmour" },
  "Reflection of the Heart": { stackSize: 2, rewardQuantity: 1, rewardName: "Kalandra's Touch", category: "UniqueArmour" },
  "Remembrance": { stackSize: 8, rewardQuantity: 1, rewardName: "Precursor's Emblem", category: "UniqueAccessory" },
  "Runic Luck": { stackSize: 4, rewardQuantity: 10, rewardName: "Vendor Refresh Currency", category: "Currency" },
  "Sambodhi's Wisdom": { stackSize: 3, rewardQuantity: 1, rewardName: "Tabula Rasa", category: "UniqueArmour" },
  "Seven Years Bad Luck": { stackSize: 13, rewardQuantity: 1, rewardName: "Mirror Shard", category: "Currency" },
  "Silence and Frost": { stackSize: 7, rewardQuantity: 1, rewardName: "The Pandemonius", category: "UniqueAccessory" },
  "Society's Remorse": { stackSize: 1, rewardQuantity: 10, rewardName: "Orb of Alteration", category: "Currency" },
  "Squandered Prosperity": { stackSize: 5, rewardQuantity: 1, rewardName: "The Light of Meaning", category: "UniqueWeapon" },
  "Succor of the Sinless": { stackSize: 6, rewardQuantity: 1, rewardName: "Bottled Faith", category: "UniqueFlask" },
  "The Academic": { stackSize: 8, rewardQuantity: 1, rewardName: "Inspired Learning", category: "UniqueWeapon" },
  "The Adventuring Spirit": { stackSize: 6, rewardQuantity: 1, rewardName: "Victario's Influence", category: "UniqueArmour" },
  "The Apothecary": { stackSize: 5, rewardQuantity: 1, rewardName: "Mageblood", category: "UniqueAccessory" },
  "The Army of Blood": { stackSize: 6, rewardQuantity: 1, rewardName: "Bloodbond", category: "UniqueAccessory" },
  "The Astromancer": { stackSize: 7, rewardQuantity: 1, rewardName: "The Eternity Shroud", category: "UniqueArmour" },
  "The Avenger": { stackSize: 12, rewardQuantity: 1, rewardName: "Mjölner", category: "UniqueWeapon" },
  "The Beast": { stackSize: 6, rewardQuantity: 1, rewardName: "Belly of the Beast", category: "UniqueArmour" },
  "The Betrayal": { stackSize: 9, rewardQuantity: 1, rewardName: "Maligaro's Virtuosity", category: "UniqueArmour" },
  "The Blazing Fire": { stackSize: 6, rewardQuantity: 1, rewardName: "Chin Sol", category: "UniqueWeapon" },
  "The Brittle Emperor": { stackSize: 8, rewardQuantity: 1, rewardName: "Voll's Devotion", category: "UniqueAccessory" },
  "The Cacophony": { stackSize: 8, rewardQuantity: 3, rewardName: "Deafening Essence", category: "Essence" },
  "The Catalyst": { stackSize: 3, rewardQuantity: 1, rewardName: "Vaal Orb", category: "Currency" },
  "The Chosen": { stackSize: 5, rewardQuantity: 1, rewardName: "Skin of the Lords", category: "UniqueArmour" },
  "The Coming Storm": { stackSize: 8, rewardQuantity: 1, rewardName: "Lightning Coil", category: "UniqueArmour" },
  "The Conduit": { stackSize: 9, rewardQuantity: 1, rewardName: "Doryani's Fist", category: "UniqueArmour" },
  "The Craving": { stackSize: 4, rewardQuantity: 1, rewardName: "Unending Hunger", category: "UniqueWeapon" },
  "The Cursed King": { stackSize: 8, rewardQuantity: 1, rewardName: "Rigwald's Curse", category: "UniqueAccessory" },
  "The Damned": { stackSize: 6, rewardQuantity: 1, rewardName: "Soul Ripper", category: "UniqueFlask" },
  "The Darkest Dream": { stackSize: 6, rewardQuantity: 1, rewardName: "Severed in Sleep", category: "UniqueArmour" },
  "The Deceiver": { stackSize: 4, rewardQuantity: 1, rewardName: "Belt of the Deceiver", category: "UniqueAccessory" },
  "The Deep Ones": { stackSize: 5, rewardQuantity: 1, rewardName: "Tidebreaker", category: "UniqueWeapon" },
  "The Demon": { stackSize: 10, rewardQuantity: 1, rewardName: "Headhunter", category: "UniqueAccessory" },
  "The Demoness": { stackSize: 5, rewardQuantity: 1, rewardName: "Death's Hand", category: "UniqueArmour" },
  "The Destination": { stackSize: 9, rewardQuantity: 1, rewardName: "Watcher's Eye", category: "UniqueJewel" },
  "The Devastator": { stackSize: 8, rewardQuantity: 1, rewardName: "Atziri's Disfavour", category: "UniqueWeapon" },
  "The Doctor": { stackSize: 8, rewardQuantity: 1, rewardName: "Headhunter", category: "UniqueAccessory" },
  "The Dreamland": { stackSize: 8, rewardQuantity: 1, rewardName: "Poorjoy's Asylum", category: "UniqueArmour" },
  "The Drunken Aristocrat": { stackSize: 8, rewardQuantity: 1, rewardName: "Divination Distillate", category: "UniqueFlask" },
  "The Endless Darkness": { stackSize: 9, rewardQuantity: 1, rewardName: "Voidforge", category: "UniqueWeapon" },
  "The Enthusiasts": { stackSize: 3, rewardQuantity: 1, rewardName: "Victario's Influence", category: "UniqueArmour" },
  "The Escape": { stackSize: 5, rewardQuantity: 1, rewardName: "Seven-League Step", category: "UniqueArmour" },
  "The Eye of Terror": { stackSize: 8, rewardQuantity: 1, rewardName: "Mageblood", category: "UniqueAccessory" },
  "The Fathomless Depths": { stackSize: 8, rewardQuantity: 1, rewardName: "Lightpoacher", category: "UniqueArmour" },
  "The Feast": { stackSize: 5, rewardQuantity: 1, rewardName: "Romira's Banquet", category: "UniqueAccessory" },
  "The Fiend": { stackSize: 11, rewardQuantity: 1, rewardName: "Headhunter", category: "UniqueAccessory" },
  "The Finishing Touch": { stackSize: 2, rewardQuantity: 1, rewardName: "Fertile Catalyst", category: "Currency" },
  "The Fletcher": { stackSize: 5, rewardQuantity: 1, rewardName: "Drillneck", category: "UniqueAccessory" },
  "The Fool": { stackSize: 4, rewardQuantity: 20, rewardName: "Orb of Chance", category: "Currency" },
  "The Formless Sea": { stackSize: 7, rewardQuantity: 1, rewardName: "Varunastra", category: "UniqueWeapon" },
  "The Forsaken": { stackSize: 7, rewardQuantity: 1, rewardName: "Umbilicus Immortalis", category: "UniqueAccessory" },
  "The Fortunate": { stackSize: 12, rewardQuantity: 2, rewardName: "Divine Orb", category: "Currency" },
  "The Fox in the Brambles": { stackSize: 7, rewardQuantity: 1, rewardName: "Bramblejack", category: "UniqueArmour" },
  "The Gemcutter": { stackSize: 3, rewardQuantity: 1, rewardName: "Gemcutter's Prism", category: "Currency" },
  "The Gladiator": { stackSize: 5, rewardQuantity: 1, rewardName: "Nightmare Bascinet", category: "UniqueArmour" },
  "The Greatest Intentions": { stackSize: 10, rewardQuantity: 1, rewardName: "The Saviour", category: "UniqueWeapon" },
  "The Gulf": { stackSize: 5, rewardQuantity: 1, rewardName: "Thread of Hope", category: "UniqueJewel" },
  "The Harvester": { stackSize: 11, rewardQuantity: 1, rewardName: "The Harvest", category: "UniqueWeapon" },
  "The Hermit": { stackSize: 9, rewardQuantity: 1, rewardName: "Lifesprig", category: "UniqueWeapon" },
  "The Heroic Shot": { stackSize: 1, rewardQuantity: 17, rewardName: "Chromatic Orb", category: "Currency" },
  "The Hive of Knowledge": { stackSize: 6, rewardQuantity: 1, rewardName: "Machina Mitts", category: "UniqueArmour" },
  "The Hoarder": { stackSize: 12, rewardQuantity: 1, rewardName: "Exalted Orb", category: "Currency" },
  "The Hunger": { stackSize: 9, rewardQuantity: 1, rewardName: "Taste of Hate", category: "UniqueFlask" },
  "The Incantation": { stackSize: 4, rewardQuantity: 1, rewardName: "The Whispering Ice", category: "UniqueWeapon" },
  "The Innocent": { stackSize: 10, rewardQuantity: 40, rewardName: "Orb of Regret", category: "Currency" },
  "The Insane Cat": { stackSize: 9, rewardQuantity: 1, rewardName: "Mageblood", category: "UniqueAccessory" },
  "The Insatiable": { stackSize: 3, rewardQuantity: 1, rewardName: "The Harvest", category: "UniqueWeapon" },
  "The Inventor": { stackSize: 6, rewardQuantity: 10, rewardName: "Vaal Orb", category: "Currency" },
  "The Journey": { stackSize: 4, rewardQuantity: 1, rewardName: "Journey Tattoo", category: "Tattoo" },
  "The King's Heart": { stackSize: 8, rewardQuantity: 1, rewardName: "Kaom's Heart", category: "UniqueArmour" },
  "The Lake": { stackSize: 8, rewardQuantity: 1, rewardName: "Reflecting Mist", category: "Currency" },
  "The Last Laugh": { stackSize: 5, rewardQuantity: 1, rewardName: "Replica Dragonfang's Flight", category: "UniqueArmour" },
  "The Last One Standing": { stackSize: 10, rewardQuantity: 1, rewardName: "Atziri's Disfavour", category: "UniqueWeapon" },
  "The Last Supper": { stackSize: 6, rewardQuantity: 1, rewardName: "Bino's Kitchen Knife", category: "UniqueWeapon" },
  "The Lich": { stackSize: 12, rewardQuantity: 1, rewardName: "Midnight Bargain", category: "UniqueWeapon" },
  "The Life Thief": { stackSize: 6, rewardQuantity: 1, rewardName: "Zerphi's Heart", category: "UniqueAccessory" },
  "The Long Con": { stackSize: 4, rewardQuantity: 1, rewardName: "Elderslayer's Exalted Orb", category: "Currency" },
  "The Long Watch": { stackSize: 3, rewardQuantity: 1, rewardName: "The Fourth Vow", category: "UniqueWeapon" },
  "The Lunaris Priestess": { stackSize: 5, rewardQuantity: 1, rewardName: "Sire of Shards", category: "UniqueWeapon" },
  "The Master Artisan": { stackSize: 5, rewardQuantity: 20, rewardName: "Quality Currency", category: "Currency" },
  "The Mayor": { stackSize: 5, rewardQuantity: 1, rewardName: "The Light of Meaning", category: "UniqueWeapon" },
  "The Mind's Eyes": { stackSize: 7, rewardQuantity: 1, rewardName: "Astral Projector", category: "UniqueAccessory" },
  "The Oath": { stackSize: 6, rewardQuantity: 1, rewardName: "Death's Oath", category: "UniqueArmour" },
  "The Offering": { stackSize: 8, rewardQuantity: 1, rewardName: "Shavronne's Wrappings", category: "UniqueArmour" },
  "The Offspring": { stackSize: 9, rewardQuantity: 1, rewardName: "Ryslatha's Coil", category: "UniqueAccessory" },
  "The One That Got Away": { stackSize: 7, rewardQuantity: 1, rewardName: "Replica Bated Breath", category: "UniqueArmour" },
  "The One With All": { stackSize: 6, rewardQuantity: 1, rewardName: "Le Heup of All", category: "UniqueAccessory" },
  "The Pack Leader": { stackSize: 6, rewardQuantity: 1, rewardName: "Alpha's Howl", category: "UniqueArmour" },
  "The Pact": { stackSize: 9, rewardQuantity: 1, rewardName: "Pledge of Hands", category: "UniqueWeapon" },
  "The Poet": { stackSize: 9, rewardQuantity: 1, rewardName: "Blood of Corruption", category: "UniqueAccessory" },
  "The Polymath": { stackSize: 3, rewardQuantity: 1, rewardName: "Astramentis", category: "UniqueAccessory" },
  "The Price of Devotion": { stackSize: 7, rewardQuantity: 1, rewardName: "Mageblood", category: "UniqueAccessory" },
  "The Price of Loyalty": { stackSize: 4, rewardQuantity: 1, rewardName: "Skin of the Loyal", category: "UniqueArmour" },
  "The Prince of Darkness": { stackSize: 6, rewardQuantity: 1, rewardName: "Elegant Hubris", category: "UniqueArmour" },
  "The Professor": { stackSize: 4, rewardQuantity: 1, rewardName: "The Putrid Cloister", category: "UniqueArmour" },
  "The Progeny of Lunaris": { stackSize: 2, rewardQuantity: 1, rewardName: "Dying Sun", category: "UniqueFlask" },
  "The Queen": { stackSize: 16, rewardQuantity: 1, rewardName: "Atziri's Acuity", category: "UniqueWeapon" },
  "The Rabbit's Foot": { stackSize: 8, rewardQuantity: 10, rewardName: "Incursion Vial", category: "Vial" },
  "The Risk": { stackSize: 3, rewardQuantity: 1, rewardName: "Ventor's Gamble", category: "UniqueAccessory" },
  "The Rusted Bard": { stackSize: 9, rewardQuantity: 4, rewardName: "Tainted Mythic Orb", category: "Currency" },
  "The Ruthless Ceinture": { stackSize: 7, rewardQuantity: 1, rewardName: "Meginord's Girdle", category: "UniqueAccessory" },
  "The Saint's Treasure": { stackSize: 10, rewardQuantity: 2, rewardName: "Exalted Orb", category: "Currency" },
  "The Samurai's Eye": { stackSize: 3, rewardQuantity: 1, rewardName: "Watcher's Eye", category: "UniqueJewel" },
  "The Scavenger": { stackSize: 8, rewardQuantity: 1, rewardName: "Carcass Jack", category: "UniqueArmour" },
  "The Scholar": { stackSize: 3, rewardQuantity: 40, rewardName: "Scroll of Wisdom", category: "Currency" },
  "The Scout": { stackSize: 8, rewardQuantity: 7, rewardName: "Exalted Orb", category: "Currency" },
  "The Seeker": { stackSize: 9, rewardQuantity: 3, rewardName: "Orb of Annulment", category: "Currency" },
  "The Sephirot": { stackSize: 11, rewardQuantity: 10, rewardName: "Divine Orb", category: "Currency" },
  "The Shieldbearer": { stackSize: 8, rewardQuantity: 1, rewardName: "The Squire", category: "UniqueArmour" },
  "The Siren": { stackSize: 7, rewardQuantity: 1, rewardName: "The Whispering Ice", category: "UniqueWeapon" },
  "The Slumbering Beast": { stackSize: 5, rewardQuantity: 1, rewardName: "Hinekora's Lock", category: "Currency" },
  "The Soul": { stackSize: 9, rewardQuantity: 1, rewardName: "Soul Taker", category: "UniqueWeapon" },
  "The Spark and the Flame": { stackSize: 2, rewardQuantity: 1, rewardName: "Berek's Respite", category: "UniqueAccessory" },
  "The Strategist": { stackSize: 6, rewardQuantity: 1, rewardName: "Inspired Learning", category: "UniqueWeapon" },
  "The Sun": { stackSize: 7, rewardQuantity: 1, rewardName: "Rise of the Phoenix", category: "UniqueArmour" },
  "The Survivalist": { stackSize: 3, rewardQuantity: 7, rewardName: "Orb of Alchemy", category: "Currency" },
  "The Sword King's Salute": { stackSize: 7, rewardQuantity: 1, rewardName: "Daresso's Salute", category: "UniqueArmour" },
  "The Throne": { stackSize: 2, rewardQuantity: 1, rewardName: "Kaom's Roots", category: "UniqueArmour" },
  "The Transformation": { stackSize: 5, rewardQuantity: 1, rewardName: "Tainted Mythic Orb", category: "Currency" },
  "The Union": { stackSize: 7, rewardQuantity: 10, rewardName: "Gemcutter's Prism", category: "Currency" },
  "The Visionary": { stackSize: 6, rewardQuantity: 1, rewardName: "Lioneye's Vision", category: "UniqueArmour" },
  "The Watcher": { stackSize: 12, rewardQuantity: 1, rewardName: "Crown of Eyes", category: "UniqueArmour" },
  "The Wedding Gift": { stackSize: 2, rewardQuantity: 1, rewardName: "Arakaali's Fang", category: "UniqueWeapon" },
  "The Whiteout": { stackSize: 8, rewardQuantity: 1, rewardName: "Cospri's Malice", category: "UniqueWeapon" },
  "The Wind": { stackSize: 7, rewardQuantity: 1, rewardName: "Windripper", category: "UniqueWeapon" },
  "The Witch": { stackSize: 8, rewardQuantity: 1, rewardName: "Kiara's Determination", category: "UniqueArmour" },
  "The Wolf's Shadow": { stackSize: 3, rewardQuantity: 1, rewardName: "Hyaon's Fury", category: "UniqueArmour" },
  "The Wolven King's Bite": { stackSize: 8, rewardQuantity: 1, rewardName: "Rigwald's Quills", category: "UniqueWeapon" },
  "The World Eater": { stackSize: 8, rewardQuantity: 1, rewardName: "Starforge", category: "UniqueWeapon" },
  "The Wrath": { stackSize: 8, rewardQuantity: 10, rewardName: "Chaos Orb", category: "Currency" },
  "Thirst for Knowledge": { stackSize: 5, rewardQuantity: 1, rewardName: "Gluttony", category: "UniqueAccessory" },
  "Three Faces in the Dark": { stackSize: 7, rewardQuantity: 3, rewardName: "Chaos Orb", category: "Currency" },
  "Three Voices": { stackSize: 3, rewardQuantity: 3, rewardName: "Essence", category: "Essence" },
  "Toxic Tidings": { stackSize: 5, rewardQuantity: 1, rewardName: "Dendrobate", category: "UniqueArmour" },
  "Tranquillity": { stackSize: 7, rewardQuantity: 1, rewardName: "Voltaxic Rift", category: "UniqueWeapon" },
  "Unchained": { stackSize: 4, rewardQuantity: 1, rewardName: "Facebreaker", category: "UniqueArmour" },
  "Underground Forest": { stackSize: 4, rewardQuantity: 10, rewardName: "Grand Eldritch Ichor", category: "Currency" },
  "Unrequited Love": { stackSize: 16, rewardQuantity: 19, rewardName: "Mirror Shard", category: "Currency" },
  "Vanity": { stackSize: 9, rewardQuantity: 1, rewardName: "Tabula Rasa", category: "UniqueArmour" },
  "Vile Power": { stackSize: 5, rewardQuantity: 1, rewardName: "Doomfletch", category: "UniqueWeapon" },
  "Vinia's Token": { stackSize: 5, rewardQuantity: 10, rewardName: "Orb of Regret", category: "Currency" },
  "When Currents Blaze": { stackSize: 2, rewardQuantity: 1, rewardName: "Stormfire", category: "UniqueWeapon" },
  "Winter's Embrace": { stackSize: 2, rewardQuantity: 1, rewardName: "Circle of Fear", category: "UniqueAccessory" },
};
